//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLKULUPLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKULUPLER()
        {
            this.TBLOGRENCİLER = new HashSet<TBLOGRENCİLER>();
        }

        public byte KULUPID { get; set; }

        //[StringLength(8, ErrorMessage = "Maksimum uzunluk 8 karakter")]
        [Required(ErrorMessage = "Kulup Adını Boş Geçemezsiniz...")]
        public string KULUPADİ { get; set; }
        [Required(ErrorMessage = "Kulup Kontenjan Boş Geçemezsiniz...")]
        public Nullable<short> KULUPKONTENJAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLOGRENCİLER> TBLOGRENCİLER { get; set; }
    }
}
